[package]
name = "call-program"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.32.1"
anyhow = "1.0"
quest = { path = "../achieve-game/programs/quest" }
reward = { path = "../achieve-game/programs/reward" }

anchor-lang = "0.32.1"
